version: "3.9"

services:
  password_manager:
    build: .
    image: password_manager
    ports:
      - "8080:10000"
    restart: always
    depends_on:
      - postgres
    container_name: password_manager

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
    container_name: postgres
