version: "3.9"

services:
  password_manager:
    build: .
    image: password_manager
    ports:
      - "8080:10000"
    restart: always
    depends_on:
      - postgres
    container_name: password_manager

  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
    container_name: postgres
    networks:
      - db_network

  migrations:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database postgres://admin:12345@postgres:5432/password_manager?sslmode=disable up
    networks:
      - db_network

networks:
  db_network:
